# Generated by Django 4.1.3 on 2022-11-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_registro',
        ),
    ]
