# Generated by Django 4.1.3 on 2022-11-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_usuario_ativa_remove_usuario_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
